name: first

on: push

jobs:
        job1: 
                name: First job
                runs-on: ubuntu-latest
                steps:
                - name: step one
                  uses: actions/checkout@v2
                - name: step two
                  run: date
                - name: Python Syntax Checker
                  uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
       
